version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: broker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: broker_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/seed-stocks.sql:/docker-entrypoint-initdb.d/seed-stocks.sql
    networks:
      - broker_network

  backend:
    build:
      context: ./backend
      dockerfile: DOCKERFILE
    container_name: broker_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: broker_db
    depends_on:
      - db
    command: ["./entrypoint.sh"]
    networks:
      - broker_network

volumes:
  db_data:

networks:
  broker_network: